services:

  eureka-server:
    build:
      context: ./EurikaServer
      dockerfile: Dockerfile
    container_name: eurika-server
    ports:
      - "8761:8761"
  
  training-microservice:
    build:
      context: ./TrainingMicroservice
      dockerfile: Dockerfile
    container_name: training-microservice
    ports:
      - "8081:8080"
    environment:
      - EUREKA_URI=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
